name: Sample Build Pipeline
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: print hello message 
        run: echo "hello mallesh this is your first pipe line "" 
        

      
  