name: Slimple workflow
on: workflow_dispatch
jobs:   
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello step
        run:  |
          echo "well come to GHA"
          echo "myname is mallesh"
          echo "3rd line"
  
