name: GitHub Actions
on:   push
jobs:   
    build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout Action
          uses: actions/checkout@v4
        - name: print intex.html file continue-on-error
          run: cat intex.html
   
     
      
