name: input-demo
on:
  workflow_dispatch:
    inputs:
      environment:
        description: choose the environment to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - test
          - prod
jobs:
  inputs-demo:
    runs-on: ubuntu-latest
    steps:
      - name: deploy the app
        run: echo "deploy the application to ${{ inputs.environment }}"
      - name: display every git hub actions context variables
        run: echo "${{toJson(github)}}"
