name: First Workflow
on:
  workflow_run:
    workflows:
      - Manual Workflow
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
          
        name: My Step
        run: echo "Hello, World!"