name: My Workflow
on: push

   jobs:
      build:
          my-job:
             runs-on: ubuntu-latest
         steps:
          name:checkout
          uses: actions/checkout@v2
          
        - name: My Step
          run: echo "Hello, World!"